name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
      
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - run: bazel run //tools:capicxx_core_tools -- --dest $(pwd)/dist $(pwd)/example/HelloWorld.fidl
